repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.32.0"
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.28.0
          - "@typescript-eslint/eslint-plugin@5.48.2"
          - "@typescript-eslint/parser@5.48.2"
